language: php

php:
  - 5.5.9
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - mysql -u root --password="" < database/database.sql

before_script:
  - cd inc/
  - cp .env-sample .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

